version: '3.8'

services:
  nmrih:
    environment:
      - LD_LIBRARY_PATH=".:bin:"
    build: nmrih
    restart: unless-stopped
    command: /bin/sh -c "./init.sh && exec ./srcds_linux -consolelog=/log/nmrih.log -game nmrih -maxplayer 8 +map nmo_broadway"
    stdin_open: true
    tty: true
    ports:
      - 27015:27015/udp
    volumes:
      - log:/log
    env_file: .env

  nmrih-fastdl:
    build: nmrih/fastdl
    ports:
      - ${NMRIH_FASTDL_PORT}:1337
    volumes:
      - ${PWD}/nmrih/fastdl/nginx.conf:/etc/nginx/nginx.conf

volumes:
  log:
